kind: ConfigMap
apiVersion: v1
metadata:
  name: demo
data:
  application.yml: |-
    chaos:
      monkey:
        watcher:
          restController: true
          service: false
        assaults:
          latency-active: true